# -*- coding: utf-8 -*-
"""csv_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEK3eveHQiMP22Js1qwak8d_qOuhO2C4
"""

import csv

def clean_csv(input_file, output_file):
    """
    Clean a CSV file by applying transformation rules.
    """
    cleaned_rows = []

    # Use 'utf-8-sig' to handle hidden Excel characters
    with open(input_file, 'r', encoding='utf-8-sig') as infile:
        # skipinitialspace=True handles "id, name" spacing issues
        reader = csv.DictReader(infile, skipinitialspace=True)
        columns = reader.fieldnames

        for row in reader:
            # 1. Skip this row if name is missing or empty
            # We use .get() to avoid errors if the column name has a hidden space
            name_val = row.get('name')
            if not name_val or name_val.strip() == '':
                continue

            # 2. Clean Age
            age = row.get('age', '').strip()
            try:
                age_value = int(age)
                if age_value <= 0:
                    row['age'] = 'UNKNOWN'
                else:
                    row['age'] = str(age_value)
            except (ValueError, TypeError):
                row['age'] = 'UNKNOWN'

            # 3. Clean Email
            if row.get('email'):
                row['email'] = row['email'].lower().strip()

            # 4. Add the row to our list (Must be inside the for loop)
            cleaned_rows.append(row)

    # 5. Write to output file (Must be outside the for loop)
    with open(output_file, 'w', encoding='utf-8', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=columns)
        writer.writeheader()
        writer.writerows(cleaned_rows)

    print(f"Cleaned {len(cleaned_rows)} rows. Output saved to {output_file}")

if __name__ == "__main__":
    input_file = "raw_users.csv"
    output_file = "clean_users.csv"
    clean_csv(input_file, output_file)

if __name__ == "__main__":
    input_file = "raw_users.csv"
    output_file = "clean_users.csv"
    clean_csv(input_file, output_file)