# -*- coding: utf-8 -*-
"""csv_quality_report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gEB8Frktvxw48pMpVNH8Eh1IckEqBUkh
"""

import csv
import json

def generate_quality_report (file_path) :
    """
    Generate a quality report for a CSV file.

    Args:
        file_path (str): Path to the CSV file

    Returns:
        dict: Quality report with metadata and statistics
    """
    pass

report = {
    "row_count": 0,
    "columns": [],
    "missing_values": {},
    "invalid_values": {}
}

def generate_quality_report(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            # We turn the 'reader' into a permanent list of data
            data = list(reader)

            report = {
                "columns": reader.fieldnames,
                "total_rows": len(data)
            }
            return report, data # Return BOTH the report and the data

    except Exception as e:
        print(f"Error: {e}")
        return None, None

# In your first Colab cell:
my_report, my_data = generate_quality_report('/content/transactions.csv')

# In your NEXT Colab cell, 'my_data' is still alive!
for row in my_data:
    print(row)

missing_counts = {col: 0 for col in report["columns"]}
invalid_counts = {}

row_count = 0
for row in my_data:
    row_count += 1
    for col in report["columns"]:
        value = row.get(col, "")
        if value == "" or value is None:
            missing_counts[col] += 1

if "amount" in row:
    try:
        amount = float(row["amount"])
        if amount <= 0:
            if "amount" not in invalid_counts:
                invalid_counts["amount"] = 0
            invalid_counts["amount"] += 1
    except (ValueError, TypeError):
        # Handle non-numeric values
        pass

report["row_count"] = row_count
report["missing_values"] = {k: v for k, v in missing_counts.items() if v > 0}
report["invalid_values"] = invalid_counts

output_file = "csv_quality_report.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(report, f, indent=2)

print(f"Quality report generated successfully: {output_file}")

if __name__ == "__main__":
    csv_file = "transactions.csv"
    report = generate_quality_report(csv_file)

    if report:
        output_file = "csv_quality_report.json"
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2)
        print(f"Quality report generated successfully: {output_file}")