# -*- coding: utf-8 -*-
"""End-to-End Spark Job.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QpwrsJdwHHw71pBhjoZGggSYk6AHVKmj
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
from pyspark.sql.window import Window
import random
from datetime import datetime, timedelta
import os

# ==============================================================================
# Part 1: Environment Setup & Data Generation
# ==============================================================================

spark = SparkSession.builder \
    .appName("StreamPulse-MerchPipeline") \
    .master("local[*]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()

# Configuration for data generation
random.seed(42)
num_orders = 300000
categories = ["T-Shirts", "Vinyl Records", "Posters", "Hoodies", "Stickers", "Accessories"]
regions = ["North America", "Europe", "Asia Pacific", "Latin America"]
payment_methods = ["credit_card", "debit_card", "paypal", "apple_pay", "gift_card"]
statuses = ["completed", "pending", "cancelled", "refunded", "failed"]
prices = {
    "T-Shirts": (15.99, 39.99),
    "Vinyl Records": (19.99, 49.99),
    "Posters": (9.99, 29.99),
    "Hoodies": (39.99, 79.99),
    "Stickers": (2.99, 9.99),
    "Accessories": (5.99, 24.99),
}

raw_data = []
base_date = datetime(2025, 1, 1)

for i in range(num_orders):
    order_date = base_date + timedelta(days=random.randint(0, 179))
    category = random.choice(categories)
    price_range = prices[category]
    unit_price = round(random.uniform(*price_range), 2)
    quantity = random.choices([1, 2, 3, 4, 5], weights=[50, 25, 15, 7, 3])[0]
    status = random.choices(statuses, weights=[70, 10, 10, 7, 3])[0]

    discount = 0.0
    if random.random() < 0.3:
        discount = random.choice([0.05, 0.10, 0.15, 0.20, 0.25])

    shipping = round(random.uniform(2.99, 12.99), 2) if unit_price * quantity > 10 else 0.0

    row = (
        f"ORD-{i+1:07d}",
        f"CUST-{random.randint(1, 80000):06d}",
        category,
        random.choice(regions),
        str(unit_price),
        str(quantity),
        str(discount),
        str(shipping),
        random.choice(payment_methods),
        status,
        order_date.strftime("%Y-%m-%d"),
        f"ART-{random.randint(1, 5000):05d}",
    )

    # Intentionally inject bad data
    if random.random() < 0.005:
        row = tuple("" if j == 4 else v for j, v in enumerate(row)) # Empty unit price
    if random.random() < 0.003:
        row = tuple("BAD_DATE" if j == 10 else v for j, v in enumerate(row)) # Bad date format

    raw_data.append(row)

raw_columns = [
    "order_id", "customer_id", "category", "region", "unit_price",
    "quantity", "discount_pct", "shipping_cost", "payment_method",
    "status", "order_date", "artist_id"]

df_raw = spark.createDataFrame(raw_data, raw_columns)
df_raw.write.csv("pipeline/raw_orders", header=True, mode="overwrite")
print(f"✅ Generated {df_raw.count()} raw orders")

# ==============================================================================
# Part 2: Inspection & Data Quality Issues
# ==============================================================================

df_inspect = spark.read.csv("pipeline/raw_orders", header=True, inferSchema=True)
print("\n--- Raw Data Inspection ---")
df_inspect.printSchema()

print("\n--- Null/Empty Counts ---")
for col_name in df_inspect.columns:
    null_count = df_inspect.filter(
        col(col_name).isNull() | (col(col_name) == "") | (col(col_name) == "null")
    ).count()
    if null_count > 0:
        print(f"  {col_name}: {null_count} nulls/empties")

# ==============================================================================
# Part 3: Clean and Transform
# ==============================================================================

#
# 3a: Explicit Schema
order_schema = StructType([
    StructField("order_id", StringType(), False),
    StructField("customer_id", StringType(), False),
    StructField("category", StringType(), True),
    StructField("region", StringType(), True),
    StructField("unit_price", DoubleType(), True),
    StructField("quantity", IntegerType(), True),
    StructField("discount_pct", DoubleType(), True),
    StructField("shipping_cost", DoubleType(), True),
    StructField("payment_method", StringType(), True),
    StructField("status", StringType(), True),
    StructField("order_date", StringType(), True),
    StructField("artist_id", StringType(), True),
])

df = spark.read.csv("pipeline/raw_orders", header=True, schema=order_schema)

# 3b: Filter Invalids
df_valid = df \
    .filter(col("order_id").isNotNull()) \
    .filter(col("unit_price").isNotNull() & (col("unit_price") > 0)) \
    .filter(col("order_date") != "BAD_DATE") \
    .filter(col("order_date").isNotNull())

# 3c: Enrichment
df_enriched = df_valid \
    .withColumn("order_date", to_date(col("order_date"), "yyyy-MM-dd")) \
    .withColumn("discount_pct", coalesce(col("discount_pct"), lit(0.0))) \
    .withColumn("shipping_cost", coalesce(col("shipping_cost"), lit(0.0))) \
    .withColumn("subtotal", round(col("unit_price") * col("quantity"), 2)) \
    .withColumn("discount_amount", round(col("subtotal") * col("discount_pct"), 2)) \
    .withColumn("total_amount", round(
        col("subtotal") - col("discount_amount") + col("shipping_cost"), 2
    )) \
    .withColumn("year", year(col("order_date"))) \
    .withColumn("month", month(col("order_date"))) \
    .withColumn("day_of_week", dayofweek(col("order_date"))) \
    .withColumn("is_weekend", when(
        dayofweek(col("order_date")).isin(1, 7), True
    ).otherwise(False))

# ==============================================================================
# Part 4: Write Curated Dataset (Partitioned Parquet)
# ==============================================================================

#
df_enriched \
    .coalesce(4) \
    .write.parquet(
        "pipeline/curated_orders",
        mode="overwrite",
        partitionBy=["year", "month"],
        compression="snappy"
    )

curated = spark.read.parquet("pipeline/curated_orders")
print(f"✅ Curated dataset created with {curated.count()} records.")

# ==============================================================================
# Part 5: Aggregated Summary Tables
# ==============================================================================

# 5.1: Daily Revenue
daily_revenue = curated \
    .filter(col("status") == "completed") \
    .groupBy("order_date") \
    .agg(
        count("order_id").alias("total_orders"),
        sum("total_amount").alias("total_revenue"),
        avg("total_amount").alias("avg_order_value"),
        countDistinct("customer_id").alias("unique_customers"),
    ) \
    .orderBy("order_date")

daily_revenue.coalesce(1).write.parquet("pipeline/summary/daily_revenue", mode="overwrite")

# 5.2: Category Performance
category_perf = curated \
    .filter(col("status") == "completed") \
    .groupBy("category") \
    .agg(
        count("order_id").alias("total_orders"),
        sum("total_amount").alias("total_revenue"),
        avg("total_amount").alias("avg_order_value"),
        avg("discount_pct").alias("avg_discount"),
        sum("quantity").alias("total_units_sold"),
    ) \
    .withColumn("revenue_rank", dense_rank().over(Window.orderBy(desc("total_revenue")))) \
    .orderBy("revenue_rank")

category_perf.coalesce(1).write.parquet("pipeline/summary/category_performance", mode="overwrite")

# 5.3: Regional Trends
regional = curated \
    .filter(col("status") == "completed") \
    .groupBy("region", "month") \
    .agg(
        count("order_id").alias("total_orders"),
        sum("total_amount").alias("total_revenue"),
        countDistinct("customer_id").alias("unique_customers"),
    ) \
    .orderBy("region", "month")

regional.coalesce(1).write.parquet("pipeline/summary/regional_trends", mode="overwrite")

# 5.4: Payment Method Analysis
payment_analysis = curated \
    .filter(col("status") == "completed") \
    .groupBy("payment_method") \
    .agg(
        count("order_id").alias("total_orders"),
        sum("total_amount").alias("total_revenue"),
        avg("total_amount").alias("avg_order_value"),
    ) \
    .withColumn("pct_of_orders", round(
        col("total_orders") / sum("total_orders").over(Window.partitionBy()), 4
    )) \
    .orderBy(desc("total_orders"))

payment_analysis.coalesce(1).write.parquet("pipeline/summary/payment_analysis", mode="overwrite")

# ==============================================================================
# Part 6: Pipeline Validation Report
# ==============================================================================

print("\n" + "=" * 60)
print("PIPELINE VALIDATION REPORT")
print("=" * 60)

raw_count = spark.read.csv("pipeline/raw_orders", header=True).count()
curated_count = curated.count()

print(f"1. Data Volume:")
print(f"   - Raw Rows: {raw_count}")
print(f"   - Curated Rows: {curated_count}")
print(f"   - Filtered: {raw_count - curated_count} ({(raw_count-curated_count)/raw_count*100:.2f}%)")

print(f"\n2. Data Quality Checks:")
null_ids = curated.filter(col("order_id").isNull()).count()
neg_amounts = curated.filter(col("total_amount") < 0).count()
print(f"   - Null order_ids: {null_ids} {'✅' if null_ids == 0 else '❌'}")
print(f"   - Negative amounts: {neg_amounts} {'✅' if neg_amounts == 0 else '❌'}")

print("\n" + "=" * 60)
print("PIPELINE COMPLETE ✅")
print("=" * 60)

# ==============================================================================
# Written Reflection
# ==============================================================================
"""
REFLECTIONS:
1. Data Quality Issues:
   - Found empty strings in unit_price causing nulls after schema application.
   - Identified 'BAD_DATE' strings in the order_date column which breaks time-based analysis.
   - Null discount/shipping costs which would break math operations if not coalesced.

2. Handling:
   - Used an explicit schema during ingestion to force correct data types.
   - Filtered out rows where primary keys (order_id) or critical metrics (unit_price, order_date) were missing.
   - Used 'coalesce' to provide default values (0.0) for optional numeric fields to maintain calculation integrity.

3. Production Changes:
   - Implement a logging system to track exactly which rows are rejected for a 'DLQ' (Dead Letter Queue).
   - Add unit tests for the transformation logic.
   - Use a metastore (like Hive or Glue) to manage the Parquet tables.
   - Automate the job using Airflow or a similar orchestrator.
"""

spark.stop()