# -*- coding: utf-8 -*-
"""Execution Plan Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArchtR9OuHIMmvOMFDLX5dajpx2kXQ2O
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import random
import os

# ==============================================================================
# PART 1: Set Up Environment and Data
# ==============================================================================

# NOTE: We intentionally disable optimizations (Broadcast and Adaptive Execution)
# to audit how Spark handles queries in a "raw" state.
spark = SparkSession.builder \
    .appName("StreamPulse-PlanAudit") \
    .master("local[*]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.sql.adaptive.enabled", "false") \
    .config("spark.sql.autoBroadcastJoinThreshold", "-1") \
    .getOrCreate()

print("✅ SparkSession created for Audit.")

# Generate StreamPulse dataset
random.seed(42)

# 1. Events (Large table - 500K rows)
events_data = []
for i in range(500000):
    events_data.append((
        f"EVT-{i+1:07d}",
        f"USR-{random.randint(1, 100000):06d}",
        f"TRK-{random.randint(1, 50000):06d}",
        f"ART-{random.randint(1, 5000):05d}",
        random.randint(10, 300),
        random.choice([True, False]),
        random.choice(["mobile", "desktop", "smart_speaker", "tablet"]),
        random.choice(["free", "premium"]),
        f"202{random.randint(3,4)}-{random.randint(1,12):02d}-{random.randint(1,28):02d}",
    ))

events_df = spark.createDataFrame(events_data,
    ["event_id", "user_id", "track_id", "artist_id", "duration_sec",
     "completed", "device", "tier", "event_date"]) \
    .withColumn("event_date", col("event_date").cast("date")) \
    .withColumn("year", year(col("event_date"))) \
    .withColumn("month", month(col("event_date")))

events_df.write.parquet("audit_data/events", mode="overwrite", partitionBy=["year"])

# 2. Artists (Small table - 5K rows)
artist_data = [(f"ART-{i+1:05d}", f"Artist {i+1}",
                random.choice(["Pop", "Rock", "Hip-Hop", "Jazz", "Electronic"]),
                random.choice(["US", "UK", "KR", "JP", "DE"])) for i in range(5000)]
artists_df = spark.createDataFrame(artist_data, ["artist_id", "name", "genre", "country"])
artists_df.write.parquet("audit_data/artists", mode="overwrite")

# 3. Tracks (Medium table - 50K rows)
track_data = [(f"TRK-{i+1:06d}", f"Track {i+1}", f"ART-{random.randint(1, 5000):05d}",
               random.randint(60, 400), random.randint(2018, 2024)) for i in range(50000)]
tracks_df = spark.createDataFrame(track_data, ["track_id", "title", "artist_id", "track_duration", "release_year"])
tracks_df.write.parquet("audit_data/tracks", mode="overwrite")

# Reload from Parquet to analyze physical plans
events = spark.read.parquet("audit_data/events")
artists = spark.read.parquet("audit_data/artists")
tracks = spark.read.parquet("audit_data/tracks")

print(f"Stats -> Events: {events.count()} | Artists: {artists.count()} | Tracks: {tracks.count()}\n")

# ==============================================================================
# PART 2: Analyze Query Plans
# ==============================================================================



print("-" * 30)
print("QUERY 1: Simple filter and select")
# Analysis: Expecting Partition Filters and Column Pruning (ReadSchema)
q1 = events.filter(col("year") == 2024) \
    .filter(col("completed") == True) \
    .select("event_id", "user_id", "duration_sec")
q1.explain(mode="formatted")

print("-" * 30)
print("QUERY 2: Events JOIN Artists (filter after join)")
# Analysis: Expecting SortMergeJoin and Shuffle (Exchange) since broadcast is disabled
q2 = events.join(artists, "artist_id") \
    .filter(col("year") == 2024) \
    .select("event_id", "name", "genre", "duration_sec")
q2.explain(mode="formatted")

print("-" * 30)
print("QUERY 3: Three-table join with aggregation")
# Analysis: Complex plan with multiple shuffles and SortMergeJoins
q3 = events.join(tracks, "track_id") \
    .join(artists, "artist_id") \
    .filter(col("year") == 2024) \
    .filter(col("genre") == "Pop") \
    .groupBy("name") \
    .agg(count("*").alias("play_count"), avg("duration_sec").alias("avg_duration"))
q3.explain(mode="formatted")



print("-" * 30)
print("QUERY 4: Multi-Action Simulation")
enriched = events.join(artists, "artist_id").filter(col("year") == 2024)
q4a = enriched.groupBy("genre").agg(count("*").alias("plays"))
q4b = enriched.groupBy("device").agg(avg("duration_sec").alias("avg_dur"))
q4a.explain(mode="formatted")
q4b.explain(mode="formatted")

print("-" * 30)
print("QUERY 5: Self-join / Aggregated reference")
popular = events.groupBy("track_id").agg(count("*").alias("play_count")) \
    .filter(col("play_count") > 10)
q5 = events.join(popular, "track_id") \
    .select("event_id", "user_id", "track_id", "play_count")
q5.explain(mode="formatted")


# ==============================================================================
# PART 3: Plan Analysis Report
# ==============================================================================
"""
# StreamPulse Execution Plan Audit Report

## Summary
- Total queries analyzed: 5
- Queries needing optimization: 4 (Q2, Q3, Q4, Q5)
- Most common issue: Inefficient Join Strategies (SortMergeJoin on tiny tables) and Redundant Recomputation.
- Estimated total improvement potential: 60-80% reduction in execution time.

## Query-by-Query Findings

### Query 1: Simple Filter
- Status: Efficient
- Issues found: None significant.
- Assessment: Spark successfully pushed 'year' to PartitionFilters and 'completed' to PushedFilters. Column pruning is active (ReadSchema is minimal).

### Query 2: Events-Artists Join
- Status: Needs Work
- Issues found: Using SortMergeJoin for a 5K row table (Artists). This triggers unnecessary shuffles (Exchange).
- Recommendation: Use BroadcastHashJoin.

### Query 3: Three-table Join
- Status: Needs Work
- Issues found: Two SortMergeJoins and multiple shuffles. Genre filter (Pop) is pushed to scan, which is good, but the overall plan is heavy.
- Recommendation: Broadcast both 'tracks' and 'artists' tables.

### Query 4: Multi-Action
- Status: Critical Issue
- Issues found: 'enriched' is used twice. Without caching, the join between Events and Artists happens twice.
- Recommendation: Cache the 'enriched' DataFrame.

### Query 5: Self-Reference Join
- Status: Needs Work
- Issues found: Events table is scanned twice.
- Recommendation: Cache 'events' or the aggregated 'popular' results if reused.
"""

# ==============================================================================
# PART 4: Optimization Proposals
# ==============================================================================

# Query 2 Optimized: Broadcast small table
q2_opt = events.filter(col("year") == 2024) \
    .join(broadcast(artists), "artist_id") \
    .select("event_id", "name", "genre", "duration_sec")

# Query 3 Optimized: Multi-broadcast & Column Pruning
q3_opt = events.filter(col("year") == 2024) \
    .select("track_id", "artist_id", "duration_sec") \
    .join(broadcast(tracks.select("track_id", "artist_id")), "track_id") \
    .join(broadcast(artists.filter(col("genre") == "Pop").select("artist_id", "name")), "artist_id") \
    .groupBy("name") \
    .agg(count("*"), avg("duration_sec"))

# Query 4 Optimized: Persistence
# enriched_opt = events.join(broadcast(artists), "artist_id").filter(col("year") == 2024).cache()

# Query 5 Optimized: Broadcast the result of the aggregation
# popular_opt = events.groupBy("track_id").agg(count("*")).filter(col("count(1)") > 10)
# q5_opt = events.join(broadcast(popular_opt), "track_id")

print("\n--- AUDIT COMPLETE ---")

'''
Priority Ranking for Fixes:
Query 4 (Caching): This is the highest priority. Redundant joins on large datasets are the biggest source of waste in Spark.

Query 2 & 3 (Broadcasting): Converting SortMergeJoin to BroadcastHashJoin for the Artists (5K) and Tracks (50K) tables will eliminate shuffles, which are the most expensive operations in Spark.

Query 1 (Validation): No changes needed; continue to monitor.

Configuration Recommendations:
spark.sql.autoBroadcastJoinThreshold: Change from -1 (disabled) to 10MB or higher (default is 10MB).

spark.sql.shuffle.partitions: Change from 200 to a number closer to the number of CPU cores in your environment (e.g., 8 or 16 for local mode) to reduce task scheduling overhead.

spark.sql.adaptive.enabled: Set to true to allow Spark to optimize join strategies and partition sizes at runtime.
'''