# -*- coding: utf-8 -*-
"""Multi-Format Data Ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfoZgUQYvm3CmuOT0c9deYx0yU1HbCwG
"""

from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *
import time
import os
import random

# ==============================================================================
# PART 1: Set Up and Create Test Data
# ==============================================================================

spark = SparkSession.builder \
    .appName("StreamPulse-DataIngestion") \
    .master("local[*]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .getOrCreate()

# 1a. Generate Artist Catalog (CSV)
random.seed(42)
genres = ["Pop", "Rock", "Hip-Hop", "Jazz", "Classical", "Electronic", "R&B", "Country"]
countries = ["US", "UK", "DE", "JP", "BR", "KR", "FR", "AU", "NG", "IN"]

artist_data = []
for i in range(50000):
    name = f"Artist_{i+1:05d}"
    genre = random.choice(genres)
    country = random.choice(countries)
    followers = random.randint(100, 5000000)
    monthly_listeners = random.randint(50, 2000000)
    verified = random.choice(["true", "false", "TRUE", "False", "yes", ""])
    join_date = f"202{random.randint(0,4)}-{random.randint(1,12):02d}-{random.randint(1,28):02d}"
    if random.random() < 0.02: followers = "NULL"
    if random.random() < 0.01: name = f'Artist "Special" {i}'
    artist_data.append((name, genre, country, str(followers), str(monthly_listeners), verified, join_date))

df_artists_raw = spark.createDataFrame(artist_data, ["artist_name", "genre", "country", "followers", "monthly_listeners", "verified", "join_date"])
df_artists_raw.write.csv("data/artists_csv", header=True, mode="overwrite", quote='"', escape='"')

# 1b. Generate Listening Events (JSON)
event_data = []
for i in range(100000):
    event_data.append({
        "event_id": f"EVT-{i+1:07d}",
        "user_id": f"USR-{random.randint(1, 20000):06d}",
        "artist_id": f"ART-{random.randint(1, 50000):05d}",
        "track_id": f"TRK-{random.randint(1, 200000):06d}",
        "duration_seconds": random.randint(10, 400),
        "completed": random.choice([True, False]),
        "timestamp": f"2025-{random.randint(1,6):02d}-{random.randint(1,28):02d}T{random.randint(0,23):02d}:{random.randint(0,59):02d}:00Z",
        "device": random.choice(["mobile", "desktop", "smart_speaker", "tablet"]),
        "quality": random.choice(["low", "standard", "high", "lossless"]),
    })
spark.createDataFrame(event_data).write.json("data/events_json", mode="overwrite")

# 1c. Generate User Profiles (Parquet)
user_data = [(f"USR-{i+1:06d}", f"user_{i+1}@email.com", random.choice(countries), random.choice(["free", "premium", "family", "student"]), random.randint(16, 75), f"202{random.randint(0,4)}-{random.randint(1,12):02d}-{random.randint(1,28):02d}") for i in range(20000)]
spark.createDataFrame(user_data, ["user_id", "email", "country", "subscription_tier", "age", "signup_date"]).write.parquet("data/users_parquet", mode="overwrite")

# ==============================================================================
# PART 2: Read the Artist Catalog (CSV)
# ==============================================================================

# Task 2a: Read without options
df_bad = spark.read.csv("data/artists_csv")
print("\n--- Task 2a: Bad CSV Read ---")
df_bad.show(5)
"""
Analysis of Task 2a:
- Column names: Not detected (treated as data in first row).
- Data types: Everything is StringType.
- First row: Contains headers.
"""

# Task 2c: Explicit Schema vs inferSchema
artist_schema = StructType([
    StructField("artist_name", StringType(), True),
    StructField("genre", StringType(), True),
    StructField("country", StringType(), True),
    StructField("followers", IntegerType(), True),
    StructField("monthly_listeners", IntegerType(), True),
    StructField("verified", StringType(), True),
    StructField("join_date", DateType(), True),
])

start = time.time()
_ = spark.read.csv("data/artists_csv", header=True, inferSchema=True, nullValue="NULL").count()
time_infer = time.time() - start

start = time.time()
df_explicit = spark.read.csv("data/artists_csv", header=True, schema=artist_schema, nullValue="NULL", dateFormat="yyyy-MM-dd")
_ = df_explicit.count()
time_explicit = time.time() - start

# Task 2d: Clean "verified" column
df_artists_clean = df_explicit.withColumn(
    "verified",
    when(lower(col("verified")).isin("true", "yes"), True)
    .when(lower(col("verified")).isin("false", "no", ""), False)
    .otherwise(None)
    .cast("boolean")
)

# ==============================================================================
# PART 3: Read Listening Events (JSON)
# ==============================================================================

start = time.time()
df_events = spark.read.json("data/events_json")
time_json = time.time() - start

df_events_enriched = df_events.withColumn(
    "event_timestamp", to_timestamp(col("timestamp"), "yyyy-MM-dd'T'HH:mm:ss'Z'")
).withColumn("event_date", to_date(col("event_timestamp"))) \
 .withColumn("event_hour", hour(col("event_timestamp"))) \
 .withColumn("event_month", month(col("event_timestamp"))) \
 .drop("timestamp")

# ==============================================================================
# PART 4: Read User Profiles (Parquet)
# ==============================================================================

start = time.time()
df_users = spark.read.parquet("data/users_parquet")
time_parquet = time.time() - start

# Demonstration of column pruning speed
start = time.time()
_ = spark.read.parquet("data/users_parquet").count()
time_all = time.time() - start

start = time.time()
_ = spark.read.parquet("data/users_parquet").select("user_id", "subscription_tier").count()
time_two = time.time() - start

# ==============================================================================
# PART 5: Format Comparison Summary
# ==============================================================================

print("\n" + "="*60)
print("PART 5: PERFORMANCE COMPARISON")
print("="*60)
print(f"{'Aspect':<25} | {'CSV':<10} | {'JSON':<10} | {'Parquet':<10}")
print("-" * 60)
print(f"{'Read Time (s)':<25} | {time_explicit:<10.3f} | {time_json:<10.3f} | {time_parquet:<10.3f}")
print(f"{'Schema Detected?':<25} | {'No':<10} | {'Yes':<10} | {'Yes':<10}")
print(f"{'Types Accurate?':<25} | {'Manual':<10} | {'Mostly':<10} | {'Perfect':<10}")
print(f"{'Data Cleaning?':<25} | {'High':<10} | {'Medium':<10} | {'Minimal':<10}")

"""
WRITTEN ANSWERS:
1. Easiest format: Parquet. It requires no options and preserves types/schemas perfectly.
2. Most cleaning: CSV. It required manual schema definition, null value handling, and complex boolean logic.
3. Best choice: Parquet. It is significantly faster and stores metadata natively.
"""

# ==============================================================================
# PART 6: Unified Output
# ==============================================================================

# Create dummy artist IDs for CSV to match JSON
df_artists_final = df_artists_clean.select(
    col("artist_name"),
    col("genre"),
    col("country").alias("artist_country"),
    col("followers")
).withColumn("artist_id", concat(lit("ART-"), lpad(monotonically_increasing_id().cast("string"), 5, "0")))

df_enriched_listens = df_events_enriched \
    .join(df_users.select("user_id", "country", "subscription_tier", "age"), on="user_id", how="left") \
    .join(df_artists_final, on="artist_id", how="left")

# Write Partitioned Output
df_enriched_listens.coalesce(4) \
    .write.parquet(
        "data/unified_listening_analytics",
        mode="overwrite",
        partitionBy=["event_month"],
        compression="snappy"
    )

print(f"\n✅ Unified dataset saved to data/unified_listening_analytics")
spark.read.parquet("data/unified_listening_analytics").show(5)

spark.stop()

'''
Key Differences in Data Formats
CSV (Comma Separated Values): A row-based text format. It has no metadata, so Spark must guess the schema or be told explicitly. It is slow to parse and does not support nested data.

JSON (JavaScript Object Notation): A row-based semi-structured format. It supports nesting but is verbose (repeats keys for every row). Spark must scan the file to determine the schema, which is computationally expensive.

Parquet: A columnar storage format. It is highly compressed and stores the schema in the file footer. It supports predicate pushdown and column pruning, allowing Spark to read only the specific data requested, making it the industry standard for analytical workloads.
'''