# -*- coding: utf-8 -*-
"""Optimize Spark Job.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TEEvJjiTRCcizR7Fb4b9wOWMK3d_aWb
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.window import Window
import random
import time
import os
import shutil

# ==============================================================================
# PART 1: SETUP & DATA GENERATION
# ==============================================================================

# ANTI-PATTERN: broadcast disabled, too many shuffle partitions for local mode
spark = SparkSession.builder \
    .appName("StreamPulse-Revenue-Lab") \
    .master("local[*]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.sql.adaptive.enabled", "false") \
    .config("spark.sql.autoBroadcastJoinThreshold", "-1") \
    .getOrCreate()

# Cleanup old data if exists
if os.path.exists("revenue_data"):
    shutil.rmtree("revenue_data")

print("✅ SparkSession created (baseline config)")

# Generate Datasets
random.seed(42)
N = 600000

# Events (Large)
event_data = [(
    f"EVT-{i+1:07d}",
    f"USR-{random.randint(1, 100000):06d}",
    f"ART-{random.randint(1, 5000):05d}",
    random.choice(["Pop", "Rock", "Hip-Hop", "Jazz", "Electronic", "R&B", "Country", "Classical"]),
    random.choice(["North America", "Europe", "Asia Pacific", "Latin America", "Africa"]),
    random.randint(15, 350),
    random.choice([True, False]),
    random.choice(["mobile", "desktop", "smart_speaker", "tablet", "car", "tv"]),
    f"2024-{random.randint(1,12):02d}-{random.randint(1,28):02d}",
) for i in range(N)]

events = spark.createDataFrame(event_data,
    ["event_id", "user_id", "artist_id", "genre", "region", "duration_sec", "completed", "device", "event_date"]) \
    .withColumn("event_date", col("event_date").cast("date"))
events.write.parquet("revenue_data/events", mode="overwrite")

# Subscriptions (Medium)
sub_data = [(f"USR-{i+1:06d}", random.choice(["free", "individual", "family", "student"]),
             round(random.choice([0.0, 9.99, 14.99, 4.99]), 2),
             random.choice(["US", "UK", "DE", "JP", "BR", "IN", "KR", "FR"])) for i in range(100000)]
spark.createDataFrame(sub_data, ["user_id", "plan", "monthly_price", "country"]).write.parquet("revenue_data/subscriptions")

# Ad rates (Tiny)
ad_data = [(g, d, round(random.uniform(1.5, 8.0), 2))
           for g in ["Pop", "Rock", "Hip-Hop", "Jazz", "Electronic", "R&B", "Country", "Classical"]
           for d in ["mobile", "desktop", "smart_speaker", "tablet", "car", "tv"]]
spark.createDataFrame(ad_data, ["ad_genre", "ad_device", "cpm"]).write.parquet("revenue_data/ad_rates")

# Payouts (Small)
payout_data = [(f"ART-{i+1:05d}", round(random.uniform(0.003, 0.008), 4), random.choice(["major", "indie", "unsigned"])) for i in range(5000)]
spark.createDataFrame(payout_data, ["artist_id", "per_stream_rate", "label_type"]).write.parquet("revenue_data/payouts")

# Reload data
events = spark.read.parquet("revenue_data/events")
subscriptions = spark.read.parquet("revenue_data/subscriptions")
ad_rates = spark.read.parquet("revenue_data/ad_rates")
payouts = spark.read.parquet("revenue_data/payouts")

# ==============================================================================
# PART 2: THE UNOPTIMIZED PIPELINE (BASELINE)
# ==============================================================================

print("\n" + "="*60)
print("RUNNING UNOPTIMIZED PIPELINE (BASELINE)")
print("="*60)

total_start = time.time()

def build_revenue_slow():
    # ANTI-PATTERN: No column pruning, recomputed constantly, SortMergeJoins everywhere
    return events \
        .join(subscriptions, "user_id") \
        .join(ad_rates, (events.genre == ad_rates.ad_genre) & (events.device == ad_rates.ad_device)) \
        .join(payouts, "artist_id") \
        .withColumn("ad_revenue", col("cpm") / 1000) \
        .withColumn("stream_payout", col("per_stream_rate"))

# Report Generation (simulating 6 distinct actions)
def run_reports(df_builder_func):
    times = []
    for i in range(1, 7):
        start = time.time()
        rev = df_builder_func()
        if i == 1: rev.groupBy("genre").agg(sum("ad_revenue"), countDistinct("user_id")).collect()
        if i == 2: rev.groupBy("region", "country").agg(count("*"), sum("ad_revenue")).collect()
        if i == 3: rev.groupBy("plan").agg(countDistinct("user_id"), count("*"), avg("duration_sec")).collect()
        if i == 4: rev.groupBy("device", "genre").agg(sum("ad_revenue"), count("*")).collect()
        if i == 5: rev.groupBy("artist_id", "label_type").agg(sum("stream_payout")).orderBy(desc("sum(stream_payout)")).limit(100).collect()
        if i == 6: rev.groupBy("event_date").agg(count("*"), sum("ad_revenue")).collect()
        times.append(time.time() - start)
    return times

report_times_baseline = run_reports(build_revenue_slow)
baseline_total = time.time() - total_start

print(f"⏱️  BASELINE TOTAL: {baseline_total:.2f}s")

# Anti-Pattern Documentation Table
"""
ANTI-PATTERN DOCUMENTATION:
1. Recomputation: build_revenue() called 6 times. Impact: Joins/Reads repeated 6x.
2. SortMergeJoin: Tiny tables (ad_rates) forced into shuffle. Impact: Expensive network I/O.
3. Shuffle Partitions: 200 partitions for local[*] (8 cores). Impact: Scheduling overhead (192 empty tasks).
4. No Column Pruning: Reading entire Parquet schemas. Impact: Unnecessary memory/disk I/O.
5. Adaptive Query Execution (AQE) Disabled: Spark cannot fix join types at runtime.
"""

# ==============================================================================
# PART 3: THE FULLY OPTIMIZED PIPELINE
# ==============================================================================

print("\n" + "="*60)
print("RUNNING FULLY OPTIMIZED PIPELINE")
print("="("-"*60))

# OPTIMIZATION: Enable Broadcast & Tune Shuffle
spark.conf.set("spark.sql.autoBroadcastJoinThreshold", "10485760") # 10MB
spark.conf.set("spark.sql.shuffle.partitions", "8") # Match local cores

opt_start = time.time()

# OPTIMIZATION: Column Pruning & Proper Join Types
revenue_opt = events.select("user_id", "artist_id", "genre", "device", "region", "duration_sec", "event_date") \
    .join(subscriptions.select("user_id", "plan", "country"), "user_id") \
    .join(broadcast(ad_rates), (col("genre") == col("ad_genre")) & (col("device") == col("ad_device"))) \
    .join(broadcast(payouts.select("artist_id", "per_stream_rate", "label_type")), "artist_id") \
    .withColumn("ad_revenue", col("cpm") / 1000) \
    .withColumn("stream_payout", col("per_stream_rate"))

# OPTIMIZATION: Caching
revenue_opt.cache()
revenue_opt.count() # Force the cache into memory

def build_revenue_optimized():
    return revenue_opt

report_times_opt = run_reports(build_revenue_optimized)
optimized_total = time.time() - opt_start

print(f"⏱️  OPTIMIZED TOTAL: {optimized_total:.2f}s")

# ==============================================================================
# PART 4: SUMMARY REPORT
# ==============================================================================

print("\n" + "="*65)
print("OPTIMIZATION REPORT — StreamPulse Revenue Pipeline")
print("="*65)

print(f"Pipeline Speedup: {baseline_total/optimized_total:.1f}x")
print(f"Time Saved:      {baseline_total - optimized_total:.2f}s ({(1-optimized_total/baseline_total)*100:.0f}% reduction)")

print("\nREPORT BREAKDOWN (Seconds):")
print("Report Type     | Baseline | Optimized | Improvement")
print("-" * 50)
report_names = ["Genre", "Regional", "Subscription", "Ad Perf", "Artist Payout", "Daily Sum"]
for name, b, o in zip(report_names, report_times_baseline, report_times_opt):
    print(f"{name:<15} | {b:>8.2f}s | {o:>9.2f}s | {b/o:>10.1f}x")

print("\nPHYSICAL PLAN IMPROVEMENTS:")
print("- BroadcastHashJoin enabled for 'ad_rates' and 'payouts'.")
print("- Exchange (Shuffle) eliminated for 2/3 joins.")
print("- Cached result set: 6 full scans reduced to 1 scan + 5 memory hits.")
print("- Shuffle Partitions reduced from 200 to 8 (Eliminated overhead).")
print("- Column Pruning: Reduced memory footprint by excluding unused ID and Flag columns.")

# Cleanup
revenue_opt.unpersist()
spark.stop()