# -*- coding: utf-8 -*-
"""pandas_regional_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JvIpb6i9YET-QflWVGcfzVdCgBsDGDg7
"""

import pandas as pd

df = pd.read_csv("regional_sales.csv")

print("Dataset Shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())

clean_df = df.dropna(subset=["quantity"])
print(f"Rows before cleaning: {len(df)}")
print(f"Rows after cleaning: {len(clean_df)}")

clean_df["quantity"] = pd.to_numeric(clean_df["quantity"], errors='coerce')
clean_df["price"] = pd.to_numeric(clean_df["price"], errors='coerce')

duplicates_before = clean_df.duplicated().sum()
clean_df = clean_df.drop_duplicates()
print(f"Duplicates removed: {duplicates_before}")

print("\nCleaned Dataset:")
print(clean_df)
print(f"\nMissing values after cleaning:\n{clean_df.isnull().sum()}")

clean_df["revenue"] = clean_df["quantity"] * clean_df["price"]
print("Dataset with revenue:")
print(clean_df[["order_id", "region", "quantity", "price", "revenue"]])

regional_summary = clean_df.groupby("region").agg({
    "revenue": "sum",
    "quantity": "sum"
}).reset_index()

regional_summary.columns = ["Region", "Total_Revenue", "Total_Quantity"]
print("\nRegional Summary:")
print(regional_summary)

top_region = regional_summary.sort_values("Total_Revenue", ascending=False).iloc[0]
print(f"\nTop-Performing Region:")
print(f"Region: {top_region['Region']}")
print(f"Total Revenue: {top_region['Total_Revenue']:,.2f}")

regional_summary_sorted = regional_summary.sort_values("Total_Revenue", ascending=False)
print("\nRegions Sorted by Revenue (High to Low):")
print(regional_summary_sorted)

low_performing = regional_summary[regional_summary["Total_Revenue"] < 5000]
print("\nLow-Performing Regions (Revenue < 5,000):")
print(low_performing)

regional_summary_sorted.to_csv("regional_revenue_summary.csv", index=False)
print("Saved: regional_revenue_summary.csv")

if len(low_performing) > 0:
    low_performing.to_csv("low_performing_regions.csv", index=False)
    print("Saved: low_performing_regions.csv")
else:
    print("No low-performing regions found (all regions above threshold)")
    # Create empty file with headers
    pd.DataFrame(columns=["Region", "Total_Revenue", "Total_Quantity"]).to_csv(
        "low_performing_regions.csv", index=False
    )

print("\n=== Analysis Summary ===")
print(f"Total Regions Analyzed: {len(regional_summary)}")
print(f"Total Revenue Across All Regions: {regional_summary['Total_Revenue'].sum():,.2f}")
print(f"Average Revenue per Region: {regional_summary['Total_Revenue'].mean():,.2f}")
print(f"Top Region: {top_region['Region']} ({top_region['Total_Revenue']:,.2f})")
print(f"Low-Performing Regions: {len(low_performing)}")

def analyze_regional_sales(input_file, revenue_threshold=5000):
    """
    Analyze regional sales performance and generate insights.

    Args:
        input_file (str): Path to the sales CSV file
        revenue_threshold (float): Threshold for low-performing regions

    Returns:
        tuple: (regional_summary, low_performing_regions)
    """
    # Load data
    df = pd.read_csv(input_file)
    print("Step 1: Dataset loaded")

    # Clean data
    clean_df = df.dropna(subset=["quantity"])
    clean_df["quantity"] = pd.to_numeric(clean_df["quantity"], errors='coerce')
    clean_df["price"] = pd.to_numeric(clean_df["price"], errors='coerce')
    clean_df = clean_df.drop_duplicates()
    print("Step 2: Data cleaned")

    # Compute revenue
    clean_df["revenue"] = clean_df["quantity"] * clean_df["price"]
    print("Step 3: Revenue calculated")

    # Aggregate by region
    regional_summary = clean_df.groupby("region").agg({
        "revenue": "sum",
        "quantity": "sum"
    }).reset_index()
    regional_summary.columns = ["Region", "Total_Revenue", "Total_Quantity"]
    regional_summary = regional_summary.sort_values("Total_Revenue", ascending=False)
    print("Step 4: Regional aggregations computed")

    # Identify low-performing regions
    low_performing = regional_summary[regional_summary["Total_Revenue"] < revenue_threshold]
    print("Step 5: Key insights identified")

    # Generate outputs
    regional_summary.to_csv("regional_revenue_summary.csv", index=False)
    if len(low_performing) > 0:
        low_performing.to_csv("low_performing_regions.csv", index=False)
    else:
        pd.DataFrame(columns=["Region", "Total_Revenue", "Total_Quantity"]).to_csv(
            "low_performing_regions.csv", index=False
        )
    print("Step 6: Output files generated")

    # Display insights
    top_region = regional_summary.iloc[0]
    print("\n=== Key Insights ===")
    print(f"Top-Performing Region: {top_region['Region']} (Revenue: {top_region['Total_Revenue']:,.2f})")
    print(f"Low-Performing Regions: {len(low_performing)}")
    if len(low_performing) > 0:
        print("Regions needing attention:")
        for _, row in low_performing.iterrows():
            print(f"  - {row['Region']}: {row['Total_Revenue']:,.2f}")

    return regional_summary, low_performing

regional_summary, low_performing = analyze_regional_sales("regional_sales.csv")

