# -*- coding: utf-8 -*-
"""pandas_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1MyJ3-G6ey5LH2R9wnUkQlx5jjv4h7Y
"""

import pandas as pd
df = pd.read_csv("sales_data.csv")

print(df)
df.head()
#df.info()
#df.describe()

region_series = df["region"]
print(type(region_series))
print(type(df))
print(region_series)

df.isnull().sum()

df.columns

df.shape

df.dtypes

print("Original dataset:")
print(df)
print(f"\nShape: {df.shape}")
print(f"\nMissing values:\n{df.isnull().sum()}")

filtered_df = df.loc[(df["region"] == "West") & (df["quantity"] > 1)]
print("Filtered dataset:")
print(filtered_df)

print("Missing values before cleaning:")
print(df.isnull().sum())

clean_df = df.dropna(subset=["quantity"])
print("Missing values after cleaning:")
print(clean_df.isnull().sum())
print(f"\nRows before: {len(df)}, Rows after: {len(clean_df)}")

print("Duplicate rows:")
print(clean_df[clean_df.duplicated()])
print(f"\nTotal duplicates: {clean_df.duplicated().sum()}")

clean_df = clean_df.drop_duplicates()

print(f"Rows after removing duplicates: {len(clean_df)}")

clean_df.to_csv("clean_sales_data.csv", index=False)

print("Clean dataset saved to: clean_sales_data.csv")
print(f"Final shape: {clean_df.shape}")

def clean_sales_data(input_file, output_file):
    """
    Clean sales data by filtering, handling missing values, and removing duplicates.
    """
    # Load data
    df = pd.read_csv(input_file)

    # Filter: region == "West" and quantity > 1
    filtered_df = df.loc[(df["region"] == "West") & (df["quantity"] > 1)]

    # Handle missing values: drop rows with missing quantity
    clean_df = filtered_df.dropna(subset=["quantity"])

    # Remove duplicates
    clean_df = clean_df.drop_duplicates()

    # Save cleaned data
    clean_df.to_csv(output_file, index=False)

    print(f"Cleaning complete!")
    print(f"Original rows: {len(df)}")
    print(f"Cleaned rows: {len(clean_df)}")
    print(f"Output saved to: {output_file}")

    return clean_df

clean_df = clean_sales_data("sales_data.csv", "clean_sales_data.csv")

print("Dataset shape:", df.shape)
print("\nFirst few rows:")
print(df.head())

df["revenue"] = df["quantity"] * df["price"]

print("Dataset with revenue:")
print(df[["order_id", "product", "quantity", "price", "revenue"]])

product_revenue = df.groupby("product")["revenue"].sum()

print("Revenue by Product:")
print(product_revenue)

product_revenue_df = product_revenue.reset_index()
product_revenue_df.columns = ["product", "total_revenue"]
print("\nRevenue by Product (DataFrame):")
print(product_revenue_df)

region_revenue = df.groupby("region")["revenue"].sum()

print("Revenue by Region:")
print(region_revenue)

region_revenue_df = region_revenue.reset_index()
region_revenue_df.columns = ["region", "total_revenue"]
print("\nRevenue by Region (DataFrame):")
print(region_revenue_df)

product_revenue_sorted = product_revenue.sort_values(ascending=False)
print("Products sorted by revenue:")
print(product_revenue_sorted)

top_products = product_revenue_sorted.head(2)
print("\nTop 2 Products by Revenue:")
print(top_products)

top_products_df = top_products.reset_index()
top_products_df.columns = ["product", "total_revenue"]
print("\nTop 2 Products (DataFrame):")
print(top_products_df)

product_revenue_df.to_csv("revenue_by_product.csv", index=False)
print("Saved: revenue_by_product.csv")

region_revenue_df.to_csv("revenue_by_region.csv", index=False)
print("Saved: revenue_by_region.csv")

top_products_df.to_csv("top_products.csv", index=False)
print("Saved: top_products.csv")

def generate_sales_analytics(input_file):
    """
    Generate sales analytics summaries from a sales dataset.
    """
    # Load data
    df = pd.read_csv(input_file)

    # Calculate revenue
    df["revenue"] = df["quantity"] * df["price"]

    # Revenue by product
    product_revenue = df.groupby("product")["revenue"].sum().reset_index()
    product_revenue.columns = ["product", "total_revenue"]
    product_revenue.to_csv("revenue_by_product.csv", index=False)

    # Revenue by region
    region_revenue = df.groupby("region")["revenue"].sum().reset_index()
    region_revenue.columns = ["region", "total_revenue"]
    region_revenue.to_csv("revenue_by_region.csv", index=False)

    # Top products
    top_products = df.groupby("product")["revenue"].sum().sort_values(ascending=False).head(2).reset_index()
    top_products.columns = ["product", "total_revenue"]
    top_products.to_csv("top_products.csv", index=False)

    print("Analytics generated successfully!")
    print(f"Total revenue: {df['revenue'].sum():,.2f}")
    print(f"Average order value: {df['revenue'].mean():,.2f}")

    return product_revenue, region_revenue, top_products

product_rev, region_rev, top_prod = generate_sales_analytics("sales_data.csv")

