# -*- coding: utf-8 -*-
"""pandas_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1MyJ3-G6ey5LH2R9wnUkQlx5jjv4h7Y
"""

import pandas as pd
df = pd.read_csv("sales_data.csv")

print(df)
df.head()
#df.info()
#df.describe()

region_series = df["region"]
print(type(region_series))
print(type(df))
print(region_series)

df.isnull().sum()

df.columns

df.shape

df.dtypes

print("Original dataset:")
print(df)
print(f"\nShape: {df.shape}")
print(f"\nMissing values:\n{df.isnull().sum()}")

filtered_df = df.loc[(df["region"] == "West") & (df["quantity"] > 1)]
print("Filtered dataset:")
print(filtered_df)

print("Missing values before cleaning:")
print(df.isnull().sum())

clean_df = df.dropna(subset=["quantity"])
print("Missing values after cleaning:")
print(clean_df.isnull().sum())
print(f"\nRows before: {len(df)}, Rows after: {len(clean_df)}")

print("Duplicate rows:")
print(clean_df[clean_df.duplicated()])
print(f"\nTotal duplicates: {clean_df.duplicated().sum()}")

clean_df = clean_df.drop_duplicates()

print(f"Rows after removing duplicates: {len(clean_df)}")

clean_df.to_csv("clean_sales_data.csv", index=False)

print("Clean dataset saved to: clean_sales_data.csv")
print(f"Final shape: {clean_df.shape}")

def clean_sales_data(input_file, output_file):
    """
    Clean sales data by filtering, handling missing values, and removing duplicates.
    """
    # Load data
    df = pd.read_csv(input_file)

    # Filter: region == "West" and quantity > 1
    filtered_df = df.loc[(df["region"] == "West") & (df["quantity"] > 1)]

    # Handle missing values: drop rows with missing quantity
    clean_df = filtered_df.dropna(subset=["quantity"])

    # Remove duplicates
    clean_df = clean_df.drop_duplicates()

    # Save cleaned data
    clean_df.to_csv(output_file, index=False)

    print(f"Cleaning complete!")
    print(f"Original rows: {len(df)}")
    print(f"Cleaned rows: {len(clean_df)}")
    print(f"Output saved to: {output_file}")

    return clean_df

clean_df = clean_sales_data("sales_data.csv", "clean_sales_data.csv")