# -*- coding: utf-8 -*-
"""pandas_inspection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1MyJ3-G6ey5LH2R9wnUkQlx5jjv4h7Y
"""

import pandas as pd
df = pd.read_csv("sales_data.csv")

print(df)
df.head()
#df.info()
#df.describe()

region_series = df["region"]
print(type(region_series))
print(type(df))
print(region_series)

df.isnull().sum()

df.columns

df.shape

df.dtypes