# -*- coding: utf-8 -*-
"""Partition Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sc8akW86vm2mzvpKzr95OMs_ccXbzEU7
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
import time, os, random

# ==============================================================================
# PART 1: Set Up and Generate Multi-Layout Data
# ==============================================================================

# NOTE: local[4] means we are simulating a cluster with 4 CPU cores.
spark = SparkSession.builder \
    .appName("StreamPulse-PartitionAudit") \
    .master("local[4]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "200") \
    .config("spark.sql.adaptive.enabled", "false") \
    .getOrCreate()

print("✅ SparkSession created (Local 4-core mode)")

# Generate 800K listening events
random.seed(42)
data = []
for i in range(800000):
    data.append((
        f"EVT-{i+1:07d}",
        f"USR-{random.randint(1, 100000):06d}",
        random.choice(["Pop", "Rock", "Hip-Hop", "Jazz", "Electronic", "R&B"]),
        random.choice(["mobile", "desktop", "smart_speaker", "tablet"]),
        random.randint(15, 350),
        random.choice([True, False]),
        f"2024-{random.randint(1,12):02d}-{random.randint(1,28):02d}",
    ))

df = spark.createDataFrame(data,
    ["event_id", "user_id", "genre", "device", "duration_sec", "completed", "event_date"]) \
    .withColumn("event_date", col("event_date").cast("date")) \
    .withColumn("month", month(col("event_date")))

# Save in multiple file layouts to see how file count affects read partitions
print("\nCreating diverse file layouts...")
if not os.path.exists("audit_data"): os.makedirs("audit_data")

for n in [1, 4, 8, 20, 100]:
    output = f"audit_data/layout_{n}"
    # Use coalesce for reduction, repartition for increase
    if n <= df.rdd.getNumPartitions():
        df.coalesce(n).write.parquet(output, mode="overwrite")
    else:
        df.repartition(n).write.parquet(output, mode="overwrite")

    file_count = len([f for f in os.listdir(output) if f.endswith(".parquet")])
    print(f"Layout {n:>3}: Created {file_count} files")


# ==============================================================================
# PART 2: Input Partition Exploration
# ==============================================================================



def partition_profile(path, label):
    df_read = spark.read.parquet(path)
    num_parts = df_read.rdd.getNumPartitions()

    # Track row distribution across partitions
    dist = df_read.withColumn("pid", spark_partition_id()) \
        .groupBy("pid").agg(count("*").alias("rows")).toPandas()

    min_rows = dist["rows"].min()
    max_rows = dist["rows"].max()
    avg_rows = dist["rows"].mean()
    ratio = max_rows / min_rows if min_rows > 0 else float("inf")

    start = time.time()
    df_read.groupBy("genre").agg(sum("duration_sec"), count("*")).collect()
    elapsed = time.time() - start

    print(f"{label:<20} parts={num_parts:<4} min={min_rows:<8.0f} max={max_rows:<8.0f} "
          f"ratio={ratio:<5.1f} groupBy={elapsed:.3f}s")
    return num_parts, elapsed

print(f"\n{'Layout':<20} {'Parts':<6} {'Min Rows':<10} {'Max Rows':<10} {'Ratio':<7} {'GroupBy'}")
print("-" * 75)
for n in [1, 4, 8, 20, 100]:
    partition_profile(f"audit_data/layout_{n}", f"Layout {n} files")


# ==============================================================================
# PART 3: Shuffle Partition Tuning
# ==============================================================================



df_tune = spark.read.parquet("audit_data/layout_8")
print(f"\n{'Shuffle Parts':<15} {'GroupBy Time':<13} {'Join Time':<13}")
print("-" * 45)

lookup = spark.createDataFrame(
    [("Pop", 1), ("Rock", 2), ("Hip-Hop", 3), ("Jazz", 4), ("Electronic", 5), ("R&B", 6)],
    ["genre", "genre_id"])

# Testing how different shuffle counts affect aggregation and joins
for n in [2, 4, 8, 16, 50, 200, 1000]:
    spark.conf.set("spark.sql.shuffle.partitions", str(n))

    start = time.time()
    df_tune.groupBy("genre", "device").agg(sum("duration_sec"), count("*")).collect()
    t_group = time.time() - start

    start = time.time()
    df_tune.join(lookup, "genre").groupBy("genre_id").agg(count("*")).collect()
    t_join = time.time() - start

    print(f"  {n:>5}         {t_group:.3f}s        {t_join:.3f}s")

# Reset to an optimal local default
spark.conf.set("spark.sql.shuffle.partitions", "8")


# ==============================================================================
# PART 4: Track Partitions Through Pipeline Stages
# ==============================================================================

df_track = spark.read.parquet("audit_data/layout_8")
stages = {}
stages["1. Read"] = df_track.rdd.getNumPartitions()

df_filtered = df_track.filter(col("completed") == True)
stages["2. Filter"] = df_filtered.rdd.getNumPartitions()

df_selected = df_filtered.select("event_id", "genre", "device", "duration_sec")
stages["3. Select"] = df_selected.rdd.getNumPartitions()

df_grouped = df_filtered.groupBy("genre").agg(count("*"))
stages["4. GroupBy"] = df_grouped.rdd.getNumPartitions()

df_sorted = df_grouped.orderBy(col("count(1)").desc())
stages["5. OrderBy"] = df_sorted.rdd.getNumPartitions()

df_coalesced = df_filtered.coalesce(4)
stages["6. Coalesce(4)"] = df_coalesced.rdd.getNumPartitions()

df_repartitioned = df_filtered.repartition(16)
stages["7. Repartition(16)"] = df_repartitioned.rdd.getNumPartitions()

print(f"\n{'Stage':<25} {'Partitions':>12} {'Change'}")
print("-" * 55)
prev = None
for stage, parts in stages.items():
    change = ""
    if prev is not None:
        if parts > prev:
            change = f"↑ increased from {prev}"
        elif parts < prev:
            change = f"↓ decreased from {prev}"
        else:
            change = "= unchanged"
    print(f"  {stage:<23} {parts:>10}   {change}")
    prev = parts


# ==============================================================================
# PART 5: Output File Control
# ==============================================================================

df_out = spark.read.parquet("audit_data/layout_8")
df_processed = df_out.filter(col("completed") == True) \
    .groupBy("genre", "month") \
    .agg(sum("duration_sec").alias("total_duration"), count("*").alias("plays"))

print("\nEvaluating Output Sizing...")
for n in [1, 4, 8, 20]:
    output_path = f"audit_data/output_{n}"
    if n <= df_processed.rdd.getNumPartitions():
        df_processed.coalesce(n).write.parquet(output_path, mode="overwrite")
    else:
        df_processed.repartition(n).write.parquet(output_path, mode="overwrite")

    files = [f for f in os.listdir(output_path) if f.endswith(".parquet")]
    total_size = sum(os.path.getsize(os.path.join(output_path, f)) for f in files)
    avg_size = total_size / len(files) if files else 0

    print(f"  {n:>2} partitions → {len(files)} files, "
          f"total {total_size/1024:.0f} KB, avg {avg_size/1024:.1f} KB/file")


# ==============================================================================
# PART 6: StreamPulse Partition Standards Document
# ==============================================================================

print("\n" + "="*65)
print("PARTITION STRATEGY DOCUMENT — StreamPulse Infrastructure Audit")
print("="*65)

report = f"""
## Environment: Local Development (4 cores)

### Input Partitions
- Target: 4 to 8 partitions.
- Match to: 1-2x core count.
- Finding: Layouts with 8-20 files performed best as they maximize core utilization
  without significant scheduling overhead.

### Shuffle Partitions
- spark.sql.shuffle.partitions: 8
- Reasoning: Settings like 200 or 1000 caused significant slowdown (up to 3x)
  due to task scheduling latency for tiny data volumes per task.

### Output Partitions
- Target file size: 128MB (ideal for HDFS/S3), though local tests used smaller sizes.
- Use coalesce() before write: 1 to 4 partitions for summary tables.
- Use partitionBy for: High-cardinality columns like 'event_date' or 'region'
  when downstream users filter frequently on them.

### Production Cluster Recommendations
- Shuffle partitions: 2-3x total executor cores.
- Target partition size: 128MB - 256MB.
- Maximum partition count: 10,000 (to avoid metadata overhead in Hive/Catalog).
"""
print(report)

spark.stop()

'''
Key Audit Findings:
The "Scheduling Overhead" is Real: In Part 3, you will notice that as shuffle partitions increase (e.g., 1000), the Join Time increases even though the data hasn't grown. This is because Spark spends more time managing task metadata than actually processing data.

Coalesce vs. Repartition: In Part 4, coalesce is shown to be more efficient for reducing partitions as it avoids a full shuffle, whereas repartition increases count but triggers an expensive data exchange.

Partition Sizing: The "Ratio" metric in Part 2 shows if your data is skewed. A high ratio (Max/Min) means one core is doing all the work while others sit idle.
'''