# -*- coding: utf-8 -*-
"""Tune Partitioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vjFJWYopYF79n854BXwxj53XgZW1k7I
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.window import Window
import random
import time

# ==============================================================================
# PART 1: Create the Skewed Pipeline & Data Generation
# ==============================================================================

spark = SparkSession.builder \
    .appName("StreamPulse-SkewFix-Lab") \
    .master("local[4]") \
    .config("spark.driver.memory", "2g") \
    .config("spark.sql.shuffle.partitions", "8") \
    .config("spark.sql.adaptive.enabled", "false") \
    .config("spark.sql.autoBroadcastJoinThreshold", "-1") \
    .getOrCreate()

print("✅ SparkSession created (Initial Baseline Config)")

# Generate skewed data
random.seed(42)
events_data = []
for i in range(800000):
    r = random.random()
    if r < 0.50:
        merchant = "MEGA_MUSIC"  # Huge Skew
    elif r < 0.60:
        merchant = "BIG_BEATS"
    elif r < 0.65:
        merchant = "SOUND_SHOP"
    elif r < 0.80:
        merchant = f"store_{random.randint(1, 200):04d}"
    else:
        merchant = None  # 20% null merchant IDs - triggers skew in joins

    events_data.append((
        f"EVT-{i+1:07d}",
        f"USR-{random.randint(1, 100000):06d}",
        merchant,
        random.choice(["Pop", "Rock", "Hip-Hop", "Jazz", "Electronic", "R&B"]),
        random.randint(15, 350),
        random.choice([True, False]),
        round(random.uniform(0.003, 0.01), 4),
    ))

events = spark.createDataFrame(events_data,
    ["event_id", "user_id", "merchant_id", "genre",
     "duration_sec", "completed", "revenue_per_stream"])

# Merchant details (small lookup table)
merchant_data = [
    ("MEGA_MUSIC", "Mega Music Inc.", "platinum", "National", 0.60),
    ("BIG_BEATS", "Big Beats Co.", "gold", "Regional", 0.55),
    ("SOUND_SHOP", "Sound Shop LLC", "silver", "Local", 0.50),
]
for i in range(1, 201):
    merchant_data.append((f"store_{i:04d}", f"Store {i}", "bronze", "Local", round(random.uniform(0.40, 0.50), 2)))

merchants = spark.createDataFrame(merchant_data, ["merchant_id", "merchant_name", "tier", "coverage", "payout_rate"])

print(f"\nSkew Analysis (Key Distribution):")
events.groupBy("merchant_id") \
    .agg(count("*").alias("cnt")) \
    .orderBy(col("cnt").desc()) \
    .withColumn("pct", round(col("cnt") / 800000 * 100, 1)) \
    .show(5)

# ==============================================================================
# PART 2: Baseline — Unoptimized Pipeline
# ==============================================================================

print("\n" + "="*60)
print("BASELINE: Unoptimized Skewed Pipeline")
print("="*60)
total_start = time.time()

joined = events.join(merchants, "merchant_id")
joined_count = joined.count()

# Report 1: Revenue by merchant
rev_by_merchant = joined.groupBy("merchant_id", "merchant_name", "tier") \
    .agg(sum(col("revenue_per_stream") * col("payout_rate")).alias("total_payout"),
         count("*").alias("streams"),
         avg("duration_sec").alias("avg_duration"))
rev_by_merchant.collect()

# Report 2: Revenue by genre
joined.groupBy("genre").agg(sum("revenue_per_stream"), count("*")).collect()

baseline_total = time.time() - total_start
print(f"⏱️  BASELINE TOTAL: {baseline_total:.3f}s")

# ==============================================================================
# PART 3: Optimizations (Incremental)
# ==============================================================================

# FIX 1: Null Handling
start = time.time()
events_valid = events.filter(col("merchant_id").isNotNull())
joined_f1 = events_valid.join(merchants, "merchant_id")
joined_f1.count()
t_fix1 = time.time() - start

# FIX 2: Broadcast Join
start = time.time()
joined_f2 = events_valid.join(broadcast(merchants), "merchant_id")
joined_f2.count()
t_fix2 = time.time() - start

# FIX 3: Salted GroupBy
start = time.time()
SALT = 10
salted = joined_f2.withColumn("salt", floor(rand() * SALT)) \
    .withColumn("salted_key", concat(col("merchant_id"), lit("_"), col("salt")))

partial = salted.groupBy("salted_key").agg(sum(col("revenue_per_stream") * col("payout_rate")).alias("p_payout"), count("*").alias("p_count"))
final = partial.withColumn("m_id", regexp_extract(col("salted_key"), "^(.+)_", 1)) \
               .groupBy("m_id").agg(sum("p_payout"), sum("p_count"))
final.collect()
t_fix3 = time.time() - start

# FIX 4: AQE (Adaptive Query Execution)
spark.conf.set("spark.sql.adaptive.enabled", "true")
spark.conf.set("spark.sql.adaptive.skewJoin.enabled", "true")
start = time.time()
joined_aqe = events_valid.join(merchants, "merchant_id") # No broadcast, let AQE fix SMJ
joined_aqe.count()
t_fix4 = time.time() - start

# ==============================================================================
# PART 4: Fully Optimized Pipeline (Production-Ready)
# ==============================================================================

print("\n" + "="*60)
print("FULLY OPTIMIZED PIPELINE (COMBINED)")
print("="*60)
total_opt_start = time.time()

# 1. Clean and persist
enriched = events.filter(col("merchant_id").isNotNull()) \
    .join(broadcast(merchants), "merchant_id") \
    .withColumn("payout", col("revenue_per_stream") * col("payout_rate")) \
    .cache()

# 2. Parallel Actions
enriched.count()
r1 = enriched.groupBy("merchant_id", "merchant_name").agg(sum("payout"), count("*")).collect()
r2 = enriched.groupBy("genre").agg(sum("revenue_per_stream"), count("*")).collect()

optimized_total = time.time() - total_opt_start
print(f"⏱️  OPTIMIZED TOTAL: {optimized_total:.3f}s")

# ==============================================================================
# PART 5: Optimization Results Summary & Written Analysis
# ==============================================================================

print("\n" + "="*65)
print("OPTIMIZATION RESULTS SUMMARY")
print("="*65)
print(f"{'Technique':<40} {'Time':>8} {'Speedup':>10}")
print("-" * 65)
print(f"{'Baseline (SortMergeJoin + Nulls)':<40} {baseline_total:>7.3f}s {'1.0x':>10}")
print(f"{'+ Null Key Filtering':<40} {t_fix1:>7.3f}s {baseline_total/t_fix1:>9.1f}x")
print(f"{'+ Broadcast Join':<40} {t_fix2:>7.3f}s {baseline_total/t_fix2:>9.1f}x")
print(f"{'+ Salted GroupBy':<40} {t_fix3:>7.3f}s {baseline_total/t_fix3:>9.1f}x")
print(f"{'+ AQE Skew Remediation':<40} {t_fix4:>7.3f}s {baseline_total/t_fix4:>9.1f}x")
print(f"{'All Combined (Production)':<40} {optimized_total:>7.3f}s {baseline_total/optimized_total:>9.1f}x")
print("=" * 65)

analysis_report = """
### WRITTEN ANALYSIS

1. Which fix had the biggest single impact?
   Broadcast Join. Because the 'merchants' table is very small, moving from a SortMergeJoin
   (which requires shuffling both large and small tables) to a BroadcastHashJoin eliminates
   the shuffle entirely for the skewed key.

2. When would salting be preferred over AQE?
   Salting is preferred when you are working on older Spark versions (pre-3.0) where AQE is not
   available, or when the skew is extremely severe in a GROUP BY operation rather than a JOIN.
   AQE's skew remediation is primarily focused on JOINs.

3. What partition-related config would you set for production?
   - spark.sql.adaptive.enabled = true
   - spark.sql.adaptive.skewJoin.enabled = true
   - spark.sql.shuffle.partitions = 'auto' (via

'''
Explanation of Techniques Used
Null Key Handling: In a join, null keys are all hashed to the same partition. By filtering them out or replacing them with unique strings before the join, we prevent a massive bottleneck on a single core.

Broadcast Join: Since the "dimension" table (Merchants) is small, we send a copy to every worker. This avoids the "Shuffle" phase entirely, which is where skew causes the most pain.

Salting: We add a random integer (the "salt") to the skewed key (e.g., MEGA_MUSIC_1, MEGA_MUSIC_2). This forces Spark to distribute the MEGA_MUSIC data across many different partitions for the initial aggregation.

AQE (Adaptive Query Execution): A native Spark feature that detects skew at runtime. If it sees one partition is much larger than others, it automatically splits that partition into smaller chunks and joins them separately.
'''